"""

The Omni USD extension is the Python frontend of extension omni.usd.core. REMINDER: For those utilities that are marked as "Internal" but opened, it means those utilities are kept for back compatibility purpose, and should not be used out of this module. They may be deprecated or removed in the future release.
"""
from __future__ import annotations
import asyncio as asyncio
import carb as carb
from enum import Enum
import functools as functools
from functools import partial
import omni as omni
from omni.kit.async_engine.async_engine import run_coroutine
from omni.usd._impl import UsdExtension
from omni.usd._impl import api
from omni.usd._impl.api import on_layers_saved_result
from omni.usd._impl.api import on_stage_result
from omni.usd._impl import layer_utils
from omni.usd._impl.layer_utils import get_all_sublayers
from omni.usd._impl.layer_utils import get_dirty_layers
from omni.usd._impl.layer_utils import get_edit_target_identifier
from omni.usd._impl.layer_utils import is_layer_locked
from omni.usd._impl.layer_utils import is_layer_writable
from omni.usd._impl.layer_utils import set_edit_target_by_identifier
from omni.usd._impl.layer_utils import stitch_prim_specs
from omni.usd._impl import prim_lists
from omni.usd._impl.prim_lists import get_geometry_standard_prim_list
from omni.usd._impl.prim_lists import get_light_prim_list
from omni.usd._impl import timesample_utils
from omni.usd._impl.timesample_utils import Value_On_Layer
from omni.usd._impl.timesample_utils import attr_has_timesample_on_key
from omni.usd._impl.timesample_utils import copy_timesamples_from_weaker_layer
from omni.usd._impl.timesample_utils import get_attribute_effective_defaultvalue_layer_info
from omni.usd._impl.timesample_utils import get_attribute_effective_timesample_layer_info
from omni.usd._impl.timesample_utils import get_attribute_effective_value_layer_info
from omni.usd._impl.timesample_utils import get_frame_time
from omni.usd._impl.timesample_utils import get_frame_time_code
from omni.usd._impl.timesample_utils import get_timesamples_count_in_authoring_layer
from omni.usd._impl import transform_helper
from omni.usd._impl.transform_helper import TransformHelper
from omni.usd._impl import utils
from omni.usd._impl.utils import PrimCaching
from omni.usd._impl.utils import can_be_copied
from omni.usd._impl.utils import can_prim_have_children
from omni.usd._impl.utils import check_ancestral
from omni.usd._impl.utils import clear_attr_val_at_time
from omni.usd._impl.utils import correct_filename_case
from omni.usd._impl.utils import create_material_input
from omni.usd._impl.utils import duplicate_prim
from omni.usd._impl.utils import find_path_in_nodes
from omni.usd._impl.utils import find_spec_on_session_or_its_sublayers
from omni.usd._impl.utils import gather_default_attributes
from omni.usd._impl.utils import get_authored_prim
from omni.usd._impl.utils import get_composed_payloads_from_prim
from omni.usd._impl.utils import get_composed_references_from_prim
from omni.usd._impl.utils import get_context_from_stage
from omni.usd._impl.utils import get_introducing_layer
from omni.usd._impl.utils import get_local_transform_SRT
from omni.usd._impl.utils import get_local_transform_matrix
from omni.usd._impl.utils import get_prim_at_path
from omni.usd._impl.utils import get_prim_descendents
from omni.usd._impl.utils import get_prop_at_path
from omni.usd._impl.utils import get_prop_auto_target_session_layer
from omni.usd._impl.utils import get_sdf_layer
from omni.usd._impl.utils import get_shader_from_material
from omni.usd._impl.utils import get_stage_next_free_path
from omni.usd._impl.utils import get_subidentifier_from_material
from omni.usd._impl.utils import get_subidentifier_from_mdl
from omni.usd._impl.utils import get_url_from_prim
from omni.usd._impl.utils import get_world_transform_matrix
from omni.usd._impl.utils import handle_exception
from omni.usd._impl.utils import is_ancestor_prim_type
from omni.usd._impl.utils import is_child_type
from omni.usd._impl.utils import is_hidden_type
from omni.usd._impl.utils import is_path_valid
from omni.usd._impl.utils import is_prim_material_supported
from omni.usd._impl.utils import is_usd_readable_filetype
from omni.usd._impl.utils import is_usd_writable_filetype
from omni.usd._impl.utils import make_path_relative_to_current_edit_target
from omni.usd._impl.utils import readable_usd_dotted_file_exts
from omni.usd._impl.utils import readable_usd_file_exts
from omni.usd._impl.utils import readable_usd_file_exts_str
from omni.usd._impl.utils import readable_usd_files_desc
from omni.usd._impl.utils import readable_usd_re
from omni.usd._impl.utils import remove_property
from omni.usd._impl.utils import set_attr_val
from omni.usd._impl.utils import set_prop_val
from omni.usd._impl.utils import writable_usd_dotted_file_exts
from omni.usd._impl.utils import writable_usd_file_exts
from omni.usd._impl.utils import writable_usd_file_exts_str
from omni.usd._impl.utils import writable_usd_files_desc
from omni.usd._impl.utils import writable_usd_re
from omni.usd._impl import watcher
from omni.usd._impl.watcher import UsdWatcher
from omni.usd._impl.watcher import get_watcher
from omni.usd._usd import AudioManager
from omni.usd._usd import EngineCreationConfig
from omni.usd._usd import EngineCreationFlags
from omni.usd._usd import OpaqueSharedHydraEngineContext
from omni.usd._usd import PickingMode
from omni.usd._usd import Selection
from omni.usd._usd import StageEventType
from omni.usd._usd import StageRenderingEventType
from omni.usd._usd import StageState
from omni.usd._usd import UsdContext
from omni.usd._usd import UsdContextInitialLoadSet
from omni.usd._usd import add_hydra_engine
from omni.usd._usd import attach_all_hydra_engines
from omni.usd._usd import create_context
from omni.usd._usd import destroy_context
from omni.usd._usd import get_context
from omni.usd._usd import get_context_from_stage_id
from omni.usd._usd import get_or_create_hydra_engine
from omni.usd._usd import merge_layers
from omni.usd._usd import merge_prim_spec
from omni.usd._usd import release_all_hydra_engines
from omni.usd._usd import release_hydra_engine
from omni.usd._usd import resolve_paths
from omni.usd._usd import resolve_prim_path_references
from omni.usd._usd import resolve_prim_paths_references
from omni.usd._usd import shutdown_usd
from pxr import Gf
from pxr import Sdf
from pxr import Tf
from pxr import Trace
from pxr import Usd
from pxr import UsdGeom
from pxr import UsdLux
from pxr import UsdShade
from pxr import UsdUtils
import re as re
import typing as typing
import weakref as weakref
from . import _impl
from . import _usd
from . import audio
from . import commands
from . import editor
__all__: list = ['EngineCreationConfig', 'EngineCreationFlags', 'OpaqueSharedHydraEngineContext', 'release_hydra_engine', 'get_or_create_hydra_engine', 'AudioManager', 'PickingMode', 'PrimCaching', 'Selection', 'StageEventType', 'StageRenderingEventType', 'StageState', 'TransformHelper', 'UsdContext', 'UsdContextInitialLoadSet', 'UsdWatcher', 'Value_On_Layer', 'add_hydra_engine', 'attach_all_hydra_engines', 'attr_has_timesample_on_key', 'can_be_copied', 'can_prim_have_children', 'check_ancestral', 'clear_attr_val_at_time', 'copy_timesamples_from_weaker_layer', 'create_context', 'create_material_input', 'destroy_context', 'duplicate_prim', 'find_path_in_nodes', 'find_spec_on_session_or_its_sublayers', 'get_all_sublayers', 'get_attribute_effective_defaultvalue_layer_info', 'get_attribute_effective_timesample_layer_info', 'get_attribute_effective_value_layer_info', 'get_authored_prim', 'get_composed_payloads_from_prim', 'get_composed_references_from_prim', 'get_context', 'get_dirty_layers', 'get_edit_target_identifier', 'get_frame_time', 'get_frame_time_code', 'get_introducing_layer', 'get_local_transform_SRT', 'get_local_transform_matrix', 'get_prim_at_path', 'get_prim_descendents', 'get_prop_at_path', 'get_sdf_layer', 'get_shader_from_material', 'get_stage_next_free_path', 'get_subidentifier_from_material', 'get_subidentifier_from_mdl', 'get_timesamples_count_in_authoring_layer', 'get_url_from_prim', 'get_watcher', 'get_world_transform_matrix', 'handle_exception', 'is_ancestor_prim_type', 'is_child_type', 'is_hidden_type', 'is_layer_locked', 'is_layer_writable', 'is_path_valid', 'is_prim_material_supported', 'is_usd_readable_filetype', 'is_usd_writable_filetype', 'make_path_relative_to_current_edit_target', 'merge_layers', 'merge_prim_spec', 'on_layers_saved_result', 'on_stage_result', 'readable_usd_dotted_file_exts', 'readable_usd_file_exts', 'readable_usd_file_exts_str', 'readable_usd_files_desc', 'readable_usd_re', 'release_all_hydra_engines', 'remove_property', 'resolve_paths', 'resolve_prim_path_references', 'resolve_prim_paths_references', 'set_attr_val', 'set_edit_target_by_identifier', 'set_prop_val', 'shutdown_usd', 'stitch_prim_specs', 'writable_usd_dotted_file_exts', 'writable_usd_file_exts', 'writable_usd_file_exts_str', 'writable_usd_files_desc', 'writable_usd_re', 'get_context_from_stage', 'get_context_from_stage_id', 'correct_filename_case', 'gather_default_attributes', 'get_prop_auto_target_session_layer', 'get_geometry_standard_prim_list', 'get_light_prim_list']
MOTION_RAYTRACING_ENABLED: _usd.EngineCreationFlags  # value = <EngineCreationFlags.MOTION_RAYTRACING_ENABLED: 1>
NONE: _usd.EngineCreationFlags  # value = <EngineCreationFlags.NONE: 0>
SKIP_ON_WORKER_PROCESS: _usd.EngineCreationFlags  # value = <EngineCreationFlags.SKIP_ON_WORKER_PROCESS: 2>
WRITABLE_USD_FILE_EXTS_STR: str = 'usd|usda|usdc|live'
