from __future__ import annotations
from omni import ui
import omni.ui._ui
__all__: list = ['ViewportDisplayDelegate']
class OverlayViewportDisplayDelegate(ViewportDisplayDelegate):
    def __del__(self):
        ...
    def __init__(self, *args, **kwargs):
        ...
    def create(self, ui_frame, prev_delegate, *args, **kwargs):
        ...
    def destroy(self):
        ...
    def set_overlay_alpha(self, overlay_alpha: float):
        ...
class ViewportDisplayDelegate:
    def __del__(self):
        ...
    def __init__(self, viewport_api):
        ...
    def create(self, ui_frame, prev_delegate, *args, **kwargs):
        ...
    def destroy(self):
        ...
    def update(self, viewport_api, texture, view, projection, presentation_key = 0):
        ...
    @property
    def image_provider(self):
        ...
    @image_provider.setter
    def image_provider(self, image_provider: omni.ui._ui.ImageProvider):
        ...
    @property
    def size(self):
        ...
