from __future__ import annotations
__all__ = ['ContentHotkeys']
class ContentHotkeys:
    """
    The Content Browser Hotkeys
    """
    def __init__(self, ext_id: str, ext_inst, window_title: str):
        ...
    def _clear_clipboard(self):
        ...
    def _copy(self):
        ...
    def _cut(self):
        ...
    def _delete(self):
        ...
    def _deregister_hotkeys(self):
        ...
    def _paste(self):
        ...
    def _register_a_hotkey(self, action_id: str, display_name: str, hotkey_string: str, action_fn: callable):
        ...
    def _register_hotkeys(self):
        ...
    def _rename(self):
        ...
    def destroy(self):
        ...
