from __future__ import annotations
import omni as omni
from omni.kit.notification_manager.notification_info import NotificationInfo
from omni.kit.notification_manager.notification_info import NotificationStatus
from omni import ui
import uuid as uuid
import weakref as weakref
__all__ = ['HOVER_AREA_DEFAULT_STYLE', 'HOVER_AREA_TRANSPARENT_STYLE', 'NotificationInfo', 'NotificationStatus', 'Prompt', 'omni', 'ui', 'uuid', 'weakref']
class Prompt:
    position_x = ...
    position_y = ...
    visible = ...
    def __enter__(self):
        ...
    def __exit__(self, type, value, trace):
        ...
    def __init__(self, notification_info: omni.kit.notification_manager.notification_info.NotificationInfo):
        ...
    def _build_ui(self, text, status, button_details):
        ...
    def destroy(self):
        ...
    def docking_to(self, window_x, window_y, window_width, window_height, offset_y = 0):
        ...
    def hide(self):
        ...
    def show(self):
        ...
    @property
    def height(self):
        ...
    @property
    def hovered(self):
        ...
    @property
    def width(self):
        ...
    @property
    def window_id(self):
        """
        Id that can be used for ui_test to query notification window.
        """
HOVER_AREA_DEFAULT_STYLE: dict = {'Rectangle::hover_area_info': {'background_color': 4293046640, 'border_radius': 10}, 'Rectangle::hover_area_warning': {'background_color': 4284401640, 'border_radius': 10}, 'Label::text': {'font_size': 14, 'color': 4278190080}, 'Image::status_warning': {'image_url': '/home/chris/isaacsim/extscache/omni.kit.notification_manager-1.0.9+d02c707b/icons/warning.svg', 'color': 4278190080}, 'Image::status_info': {'image_url': '/home/chris/isaacsim/extscache/omni.kit.notification_manager-1.0.9+d02c707b/icons/info.svg', 'color': 4278190080}, 'Button:hovered': {'background_color': 4288585374}}
HOVER_AREA_TRANSPARENT_STYLE: dict = {'background_color': 0, 'background_gradient_color': 0, 'background_selected_color': 0, 'border_color': 0, 'color': 0, 'selected_color': 0, 'secondary_color': 0, 'secondary_selected_color': 0, 'debug_color': 0}
