from __future__ import annotations
import omni as omni
from usdrt.PhysxSchema._PhysxSchema import JointStateAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxArticulationAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxArticulationForceSensorAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxAutoAttachmentAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxAutoParticleClothAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxCameraAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxCameraDroneAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxCameraFollowAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxCameraFollowLookAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxCameraFollowVelocityAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxCharacterControllerAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxCollisionAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxContactReportAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxConvexDecompositionCollisionAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxConvexHullCollisionAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxCookedDataAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxDeformableAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxDeformableBodyAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxDeformableBodyMaterialAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxDeformableSurfaceAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxDeformableSurfaceMaterialAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxDiffuseParticlesAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxForceAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxHairAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxHairMaterialAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxJointAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxLimitAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxMaterialAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxMeshMergeCollisionAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxPBDMaterialAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxParticleAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxParticleAnisotropyAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxParticleClothAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxParticleIsosurfaceAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxParticleSamplingAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxParticleSetAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxParticleSmoothingAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxParticleSystem
from usdrt.PhysxSchema._PhysxSchema import PhysxPhysicsAttachment
from usdrt.PhysxSchema._PhysxSchema import PhysxPhysicsDistanceJointAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxPhysicsGearJoint
from usdrt.PhysxSchema._PhysxSchema import PhysxPhysicsInstancer
from usdrt.PhysxSchema._PhysxSchema import PhysxPhysicsJointInstancer
from usdrt.PhysxSchema._PhysxSchema import PhysxPhysicsRackAndPinionJoint
from usdrt.PhysxSchema._PhysxSchema import PhysxRigidBodyAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxSDFMeshCollisionAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxSceneAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxSceneQuasistaticAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxSphereFillCollisionAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxSurfaceVelocityAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxTendonAttachmentAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxTendonAttachmentLeafAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxTendonAttachmentRootAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxTendonAxisAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxTendonAxisRootAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxTriangleMeshCollisionAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxTriangleMeshSimplificationCollisionAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxTriggerAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxTriggerStateAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleAckermannSteeringAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleAutoGearBoxAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleBrakesAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleClutchAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleContextAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleControllerAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleDriveBasicAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleDriveStandardAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleEngineAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleGearsAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleMultiWheelDifferentialAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleNonlinearCommandResponseAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleSteeringAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleSuspensionAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleSuspensionComplianceAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleTankControllerAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleTankDifferentialAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleTireAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleTireFrictionTable
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleWheelAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleWheelAttachmentAPI
from usdrt.PhysxSchema._PhysxSchema import PhysxVehicleWheelControllerAPI
from usdrt.PhysxSchema._PhysxSchema import TetrahedralMesh
from usdrt.PhysxSchema._PhysxSchema import Tokens
from usdrt import Sdf
from . import _PhysxSchema
__all__ = ['JointStateAPI', 'PhysxArticulationAPI', 'PhysxArticulationForceSensorAPI', 'PhysxAutoAttachmentAPI', 'PhysxAutoParticleClothAPI', 'PhysxCameraAPI', 'PhysxCameraDroneAPI', 'PhysxCameraFollowAPI', 'PhysxCameraFollowLookAPI', 'PhysxCameraFollowVelocityAPI', 'PhysxCharacterControllerAPI', 'PhysxCollisionAPI', 'PhysxContactReportAPI', 'PhysxConvexDecompositionCollisionAPI', 'PhysxConvexHullCollisionAPI', 'PhysxCookedDataAPI', 'PhysxDeformableAPI', 'PhysxDeformableBodyAPI', 'PhysxDeformableBodyMaterialAPI', 'PhysxDeformableSurfaceAPI', 'PhysxDeformableSurfaceMaterialAPI', 'PhysxDiffuseParticlesAPI', 'PhysxForceAPI', 'PhysxHairAPI', 'PhysxHairMaterialAPI', 'PhysxJointAPI', 'PhysxLimitAPI', 'PhysxMaterialAPI', 'PhysxMeshMergeCollisionAPI', 'PhysxPBDMaterialAPI', 'PhysxParticleAPI', 'PhysxParticleAnisotropyAPI', 'PhysxParticleClothAPI', 'PhysxParticleIsosurfaceAPI', 'PhysxParticleSamplingAPI', 'PhysxParticleSetAPI', 'PhysxParticleSmoothingAPI', 'PhysxParticleSystem', 'PhysxPhysicsAttachment', 'PhysxPhysicsDistanceJointAPI', 'PhysxPhysicsGearJoint', 'PhysxPhysicsInstancer', 'PhysxPhysicsJointInstancer', 'PhysxPhysicsRackAndPinionJoint', 'PhysxRigidBodyAPI', 'PhysxSDFMeshCollisionAPI', 'PhysxSceneAPI', 'PhysxSceneQuasistaticAPI', 'PhysxSphereFillCollisionAPI', 'PhysxSurfaceVelocityAPI', 'PhysxTendonAttachmentAPI', 'PhysxTendonAttachmentLeafAPI', 'PhysxTendonAttachmentRootAPI', 'PhysxTendonAxisAPI', 'PhysxTendonAxisRootAPI', 'PhysxTriangleMeshCollisionAPI', 'PhysxTriangleMeshSimplificationCollisionAPI', 'PhysxTriggerAPI', 'PhysxTriggerStateAPI', 'PhysxVehicleAPI', 'PhysxVehicleAckermannSteeringAPI', 'PhysxVehicleAutoGearBoxAPI', 'PhysxVehicleBrakesAPI', 'PhysxVehicleClutchAPI', 'PhysxVehicleContextAPI', 'PhysxVehicleControllerAPI', 'PhysxVehicleDriveBasicAPI', 'PhysxVehicleDriveStandardAPI', 'PhysxVehicleEngineAPI', 'PhysxVehicleGearsAPI', 'PhysxVehicleMultiWheelDifferentialAPI', 'PhysxVehicleNonlinearCommandResponseAPI', 'PhysxVehicleSteeringAPI', 'PhysxVehicleSuspensionAPI', 'PhysxVehicleSuspensionComplianceAPI', 'PhysxVehicleTankControllerAPI', 'PhysxVehicleTankDifferentialAPI', 'PhysxVehicleTireAPI', 'PhysxVehicleTireFrictionTable', 'PhysxVehicleWheelAPI', 'PhysxVehicleWheelAttachmentAPI', 'PhysxVehicleWheelControllerAPI', 'Sdf', 'TetrahedralMesh', 'Tokens', 'omni']
__copyright__: str = 'Copyright (c) 2020-2021, NVIDIA CORPORATION. All rights reserved.'
__license__: str = '\nNVIDIA CORPORATION and its licensors retain all intellectual property\nand proprietary rights in and to this software, related documentation\nand any modifications thereto. Any use, reproduction, disclosure or\ndistribution of this software and related documentation without an express\nlicense agreement from NVIDIA CORPORATION is strictly prohibited.\n'
