"""

        This module contains bindings to C++ omni::kit::renderer::IRenderer interface, core C++ part of Omniverse Kit.

        >>> import omni.kit.renderer.bind
        >>> e = omni.kit.renderer.bind.get_renderer_interface()
        
"""
from __future__ import annotations
import carb._carb
import carb.events._events
import omni.appwindow._appwindow
import omni.gpu_foundation_factory._gpu_foundation_factory
__all__ = ['IRenderer', 'acquire_renderer_interface', 'release_renderer_interface']
class IRenderer:
    def attach_app_window(self, arg0: omni.appwindow._appwindow.IAppWindow) -> bool:
        ...
    def detach_app_window(self, arg0: omni.appwindow._appwindow.IAppWindow) -> None:
        ...
    def draw_freeze_app_window(self, arg0: omni.appwindow._appwindow.IAppWindow, arg1: bool) -> None:
        ...
    def force_render_frame(self, arg0: float) -> None:
        ...
    def freeze_app_window(self, arg0: omni.appwindow._appwindow.IAppWindow, arg1: bool) -> None:
        ...
    def get_clear_color(self, arg0: omni.appwindow._appwindow.IAppWindow) -> carb._carb.Float4:
        ...
    def get_framebuffer_height(self, arg0: omni.appwindow._appwindow.IAppWindow) -> int:
        ...
    def get_framebuffer_texture(self, arg0: omni.appwindow._appwindow.IAppWindow) -> omni.gpu_foundation_factory._gpu_foundation_factory.Texture:
        ...
    def get_framebuffer_width(self, arg0: omni.appwindow._appwindow.IAppWindow) -> int:
        ...
    def get_graphics_command_list(self, arg0: int) -> ...:
        ...
    def get_graphics_command_queue(self, arg0: omni.appwindow._appwindow.IAppWindow) -> ...:
        ...
    def get_graphics_device(self, arg0: omni.appwindow._appwindow.IAppWindow) -> omni.gpu_foundation_factory._gpu_foundation_factory.Device:
        ...
    def get_post_end_render_frame_event_stream(self, app_window: omni.appwindow._appwindow.IAppWindow = None) -> carb.events._events.IEventStream:
        ...
    def get_post_end_render_pass_event_stream(self, app_window: omni.appwindow._appwindow.IAppWindow = None) -> carb.events._events.IEventStream:
        ...
    def get_post_present_frame_buffer_event_stream(self, app_window: omni.appwindow._appwindow.IAppWindow = None) -> carb.events._events.IEventStream:
        ...
    def get_pre_begin_frame_event_stream(self, app_window: omni.appwindow._appwindow.IAppWindow = None) -> carb.events._events.IEventStream:
        ...
    def get_pre_begin_render_pass_event_stream(self, app_window: omni.appwindow._appwindow.IAppWindow = None) -> carb.events._events.IEventStream:
        ...
    def get_render_frame_event_stream(self, app_window: omni.appwindow._appwindow.IAppWindow = None) -> carb.events._events.IEventStream:
        ...
    def is_app_window_attached(self, arg0: omni.appwindow._appwindow.IAppWindow) -> bool:
        ...
    def set_clear_color(self, arg0: omni.appwindow._appwindow.IAppWindow, arg1: carb._carb.Float4) -> None:
        ...
    def shutdown(self) -> None:
        ...
    def startup(self) -> None:
        ...
    def wait_idle(self, arg0: omni.appwindow._appwindow.IAppWindow) -> None:
        ...
    @property
    def clear_color(self, arg1: omni.appwindow._appwindow.IAppWindow) -> carb._carb.Float4:
        """
        App window clear color
        """
    @clear_color.setter
    def clear_color(self, arg1: omni.appwindow._appwindow.IAppWindow, arg2: carb._carb.Float4) -> None:
        ...
def acquire_renderer_interface(plugin_name: str = None, library_path: str = None) -> IRenderer:
    ...
def release_renderer_interface(arg0: IRenderer) -> None:
    ...
