from __future__ import annotations
import omni as omni
__all__ = ['RenderPropertiesExtension', 'omni']
class RenderPropertiesExtension(omni.ext._extensions.IExt):
    def _RenderPropertiesExtension__register_widgets(self):
        ...
    def _RenderPropertiesExtension__unregister_widgets(self):
        ...
    def __init__(self):
        ...
    def on_shutdown(self):
        ...
    def on_startup(self, ext_id):
        ...
