from __future__ import annotations
import carb as carb
import omni as omni
from omni.kit.widget.layers.layer_model_utils import LayerModelUtils
from omni.kit.widget.layers.prim_spec_item import PrimSpecItem
import weakref as weakref
__all__ = ['ACTIONS_TAG', 'ACTION_DELETE_PRIM_SPEC_ITEMS', 'Action', 'ActionManager', 'LayerModelUtils', 'PrimSpecItem', 'carb', 'omni', 'weakref']
class Action:
    def __init__(self, extension_name: str, action_name: str, action_display_name: str, action_description: str, on_action_fn: typing.Callable[[], NoneType], hotkey: carb.input.KeyboardInput, modifiers: int = 0):
        ...
    def _register(self):
        ...
    def _register_hotkey(self):
        ...
    def _unregister_hotkey(self):
        ...
    def destroy(self):
        ...
class ActionManager:
    def _ActionManager__register_hotkeys(self):
        ...
    def _ActionManager__unregister_hotkeys(self):
        ...
    def __init__(self):
        ...
    def on_shutdown(self):
        ...
    def on_startup(self, layer_extension):
        ...
ACTIONS_TAG: str = 'Layers Actions'
ACTION_DELETE_PRIM_SPEC_ITEMS: str = 'delete_deltas'
