from __future__ import annotations
import carb as carb
from omni.kit.usd import layers
from omni.kit.widget.layers.singleton import Singleton
__all__: list = ['LayerSettings']
SETTINGS_CONTINOUS_UPDATE_IN_AUTO_AUTHORING: str = '/persistent/app/layersinterface/continousUpdate'
SETTINGS_ENABLE_AUTO_AUTHORING_MODE: str = '/persistent/app/layerwindow/enableAutoAuthoringMode'
SETTINGS_ENABLE_SPEC_LINKING_MODE: str = '/persistent/app/layerwindow/enableSpecLinkingMode'
SETTINGS_FILE_DIALOG_SHOW_ROOT_LAYER_LOCATION: str = '/persistent/app/layerwindow/filedialog/showRootLayerLocation'
SETTINGS_SHOW_INFO_NOTIFICATION: str = '/persistent/app/layerwindow/showInfoNotification'
SETTINGS_SHOW_LAYER_CONTENTS: str = '/persistent/app/layerwindow/showLayerContents'
SETTINGS_SHOW_LAYER_FILE_EXTENSION: str = '/persistent/app/layerwindow/showLayerFileExtension'
SETTINGS_SHOW_MERGE_OR_FLATTEN_WARNING: str = '/persistent/app/layerwindow/showMergeOrFlattenWarning'
SETTINGS_SHOW_METRICSASSEMBLER_LAYER: str = '/persistent/app/layerwindow/showMetricsAssemblerLayer'
SETTINGS_SHOW_MISSING_REFERENCE: str = '/persistent/app/layerwindow/showMissingReference'
SETTINGS_SHOW_SESSION_LAYER: str = '/persistent/app/layerwindow/showSessionLayer'
SETTINGS_SHOW_WARNING_NOTIFICATION: str = '/persistent/app/layerwindow/showWarningNotification'
