from __future__ import annotations
import calendar as calendar
import datetime as datetime
import dateutil as dateutil
from dateutil.parser._parser import parse as date_parser
from omni import ui
import omni.ui._ui
__all__ = ['DateModel', 'TimeModel', 'ZoneModel', 'calendar', 'date_parser', 'datetime', 'dateutil', 'ui']
class DateModel(omni.ui._ui.AbstractValueModel):
    day = ...
    month = ...
    year = ...
    def __init__(self, _datetime: datetime.datetime = None):
        ...
    def _adjust_day(self, year, month):
        ...
    def get_value_as_string(self):
        ...
    def set_value(self, dt_string: str):
        ...
class TimeModel(omni.ui._ui.AbstractValueModel):
    hour = ...
    minute = ...
    second = ...
    def __init__(self, _datetime: datetime.datetime = None):
        ...
    def get_value_as_string(self):
        ...
    def set_value(self, dt_string: str):
        ...
class ZoneModel(omni.ui._ui.AbstractValueModel):
    def __init__(self, _datetime: datetime.datetime = None):
        ...
    def get_value_as_string(self):
        ...
    def set_value(self, tz: datetime.timezone):
        ...
    @property
    def timezone(self):
        ...
