from __future__ import annotations
__all__ = ['addActor', 'addBoxCollisionShape', 'addCollisionShape', 'addDensity', 'addDisplayColor', 'addGroundPlane', 'addGroundTriMesh', 'addOrientation', 'addPhysicsScene', 'addPosition', 'addRigidBody', 'addRigidBox', 'addRigidBoxForInstancing', 'addRigidCapsule', 'addRigidCone', 'addRigidCylinder', 'addRigidSphere', 'addVelocity', 'createMesh', 'createMeshBox', 'createMeshCapsule', 'createMeshCylinder', 'createMeshSphere', 'createMeshSquare', 'decodeSdfPath', 'encodeSdfPath', 'getMassSpaceInertia', 'intToSdfPath', 'sdfPathToInt']
def addActor(*args, **kwargs):
    ...
def addBoxCollisionShape(*args, **kwargs):
    ...
def addCollisionShape(*args, **kwargs):
    ...
def addDensity(*args, **kwargs):
    ...
def addDisplayColor(*args, **kwargs):
    ...
def addGroundPlane(*args, **kwargs):
    ...
def addGroundTriMesh(*args, **kwargs):
    ...
def addOrientation(*args, **kwargs):
    ...
def addPhysicsScene(*args, **kwargs):
    ...
def addPosition(*args, **kwargs):
    ...
def addRigidBody(*args, **kwargs):
    ...
def addRigidBox(*args, **kwargs):
    ...
def addRigidBoxForInstancing(*args, **kwargs):
    ...
def addRigidCapsule(*args, **kwargs):
    ...
def addRigidCone(*args, **kwargs):
    ...
def addRigidCylinder(*args, **kwargs):
    ...
def addRigidSphere(*args, **kwargs):
    ...
def addVelocity(*args, **kwargs):
    ...
def createMesh(*args, **kwargs):
    ...
def createMeshBox(*args, **kwargs):
    ...
def createMeshCapsule(*args, **kwargs):
    ...
def createMeshCylinder(*args, **kwargs):
    ...
def createMeshSphere(*args, **kwargs):
    ...
def createMeshSquare(*args, **kwargs):
    ...
def decodeSdfPath(*args, **kwargs):
    ...
def encodeSdfPath(*args, **kwargs):
    ...
def getMassSpaceInertia(*args, **kwargs):
    ...
def intToSdfPath(*args, **kwargs):
    ...
def sdfPathToInt(*args, **kwargs):
    ...
__MFB_FULL_PACKAGE_NAME: str = 'physicsSchemaTools'
