from __future__ import annotations
import typing
import weakref as weakref
__all__: list = ['DragDropDelegate']
class DragDropDelegate:
    _DragDropDelegate__g_registered: typing.ClassVar[list]  # value = [<weakref at 0x709fadb33d30; to 'UsdFileDropDelegate' at 0x709fadb35f90>, <weakref at 0x709fadb33c90; to 'UsdShadeDropDelegate' at 0x709faa156e90>, <weakref at 0x709fadb33e20; to 'MaterialFileDropDelegate' at 0x709faa156230>, <weakref at 0x709fbe3e5df0; to 'AudioFileDropDelegate' at 0x709faa157640>]
    @classmethod
    def get_instances(cls):
        ...
    def __del__(self):
        ...
    def __init__(self):
        ...
    def accepted(self, drop_data: dict) -> bool:
        ...
    def cancel(self, drop_data: dict) -> None:
        ...
    def destroy(self):
        ...
    def dropped(self, drop_data: dict) -> None:
        ...
    def update_drop_position(self, drop_data: dict) -> bool:
        ...
    @property
    def add_outline(self) -> bool:
        ...
