from __future__ import annotations
import typing
import weakref as weakref
__all__: list = ['DragDropDelegate']
class DragDropDelegate:
    _DragDropDelegate__g_registered: typing.ClassVar[list]  # value = [<weakref at 0x7032e41671f0; to 'UsdFileDropDelegate' at 0x703302feb350>, <weakref at 0x7032e41671a0; to 'UsdShadeDropDelegate' at 0x70332417d190>, <weakref at 0x7032e4167150; to 'MaterialFileDropDelegate' at 0x70332417a690>, <weakref at 0x7032e4167100; to 'AudioFileDropDelegate' at 0x7032e41052d0>]
    @classmethod
    def get_instances(cls):
        ...
    def __del__(self):
        ...
    def __init__(self):
        ...
    def accepted(self, drop_data: dict) -> bool:
        ...
    def cancel(self, drop_data: dict) -> None:
        ...
    def destroy(self):
        ...
    def dropped(self, drop_data: dict) -> None:
        ...
    def update_drop_position(self, drop_data: dict) -> bool:
        ...
    @property
    def add_outline(self) -> bool:
        ...
