from __future__ import annotations
import carb as carb
import omni as omni
from omni.kit.viewport.window.dragdrop.scene_drop_delegate import SceneDropDelegate
import os as os
import pxr.Gf
from pxr import Gf
from pxr import Sdf
from pxr import Usd
from pxr import UsdGeom
__all__: list = ['UsdFileDropDelegate']
class UsdFileDropDelegate(omni.kit.viewport.window.dragdrop.scene_drop_delegate.SceneDropDelegate):
    def __init__(self, preview_setting: str = None, **kwargs):
        ...
    def accepted(self, drop_data: dict):
        ...
    def add_alternate_drop_marker(self, drop_data: dict, world_space_pos: pxr.Gf.Vec3d):
        ...
    def add_drop_marker(self, drop_data: dict, world_space_pos: pxr.Gf.Vec3d):
        ...
    def add_usd_drop_marker(self, drop_data: dict, world_space_pos: pxr.Gf.Vec3d, pickable_collection: bool = False):
        ...
    def drop_should_disable_preview(self):
        ...
    def dropped(self, drop_data: dict):
        ...
    def ignore_url(self, url: str):
        ...
    def remove_alternate_drop_marker(self, drop_data: dict):
        ...
    def remove_drop_marker(self, drop_data: dict):
        ...
    def reset_state(self):
        ...
    def update_pickability(self, drop_data: dict, pickable: bool):
        ...
