from __future__ import annotations
import numpy as np
__all__ = ['cos', 'inverse', 'matmul', 'np', 'sin', 'transpose_2d']
def cos(data):
    ...
def inverse(data):
    ...
def matmul(matrix_a, matrix_b):
    ...
def sin(data):
    ...
def transpose_2d(data):
    ...
