from __future__ import annotations
import omni.ui.color_utils
import pathlib
from pathlib import Path
__all__ = ['CURRENT_PATH', 'ICON_PATH', 'Path', 'SAVE_WINDOW_STYLE', 'UI_STYLE', 'cl']
CURRENT_PATH: pathlib.PosixPath  # value = PosixPath('/home/chris/isaacsim/extscache/omni.kit.viewport.menubar.settings-107.0.3+d02c707b/omni/kit/viewport/menubar/settings')
ICON_PATH: pathlib.PosixPath  # value = PosixPath('/home/chris/isaacsim/extscache/omni.kit.viewport.menubar.settings-107.0.3+d02c707b/data/icons')
SAVE_WINDOW_STYLE: dict  # value = {'Window': {'secondary_background_color': 0}, 'Titlebar.Background': {'background_color': 'save_background'}, 'Input.Hint': {'color': 'input_hint'}, 'Image::close': {'image_url': '/home/chris/isaacsim/extscache/omni.kit.viewport.menubar.settings-107.0.3+d02c707b/data/icons/close.svg'}, 'Button': {'background_color': 'save_background'}}
UI_STYLE: dict  # value = {'Menu.Item.Icon::Settings': {'image_url': '/home/chris/isaacsim/extscache/omni.kit.viewport.menubar.settings-107.0.3+d02c707b/data/icons/viewport_settings.svg'}, 'ResolutionLink': {'background_color': 0, 'margin': 0, 'padding': 2}, 'ResolutionLink.Image': {'image_url': '/home/chris/isaacsim/extscache/omni.kit.viewport.menubar.settings-107.0.3+d02c707b/data/icons/link_dark.svg', 'margin': 0}, 'ResolutionLink.Image:checked': {'image_url': '/home/chris/isaacsim/extscache/omni.kit.viewport.menubar.settings-107.0.3+d02c707b/data/icons/link.svg'}, 'ComboBox::ratio': {'background_color': 0, 'padding': 4, 'margin': 0}, 'Menu.Item.Button::save': {'padding': 0, 'margin': 0, 'background_color': 0}, 'Menu.Item.Button.Image::save': {'image_url': '/home/chris/isaacsim/extscache/omni.kit.viewport.menubar.settings-107.0.3+d02c707b/data/icons/save.svg', 'color': 'viewport_menubar_light'}, 'Menu.Item.Button.Image::save:checked': {'color': 'shade:4291663622'}, 'Ratio.Background': {'background_color': 4282664004, 'border_color': 4288770075, 'border_width': 1}, 'Resolution.Text': {'color': 'input_hint'}, 'Resolution.Name': {'color': 'viewport_menubar_light'}, 'Resolution.Del': {'image_url': '/home/chris/isaacsim/extscache/omni.kit.viewport.menubar.settings-107.0.3+d02c707b/data/icons/delete.svg'}}
cl: omni.ui.color_utils.ColorShade  # value = <omni.ui.color_utils.ColorShade object>
