from __future__ import annotations
import carb as carb
import omni as omni
from omni.kit.property.usd.prim_selection_payload import PrimSelectionPayload
from omni import ui
import pxr.Sdf
from pxr import Sdf
import weakref as weakref
__all__: list = list()
class AddAttributePopup:
    def __del__(self):
        ...
    def __init__(self):
        ...
    def click_fn(self, payload: omni.kit.property.usd.prim_selection_payload.PrimSelectionPayload):
        ...
    def destroy(self):
        ...
    def show_fn(self, objects: dict):
        ...
class ComboBoxModel(omni.ui._ui.AbstractItemModel):
    def __init__(self):
        ...
    def _populate_items(self):
        ...
    def get_item_children(self, item):
        ...
    def get_item_value_model(self, item, column_id):
        ...
    def get_selected_item(self):
        ...
class ValueTypeNameItem(omni.ui._ui.AbstractItem):
    def __init__(self, value_type_name: pxr.Sdf.ValueTypeName, value_type_name_str: str):
        ...
class ValueTypeNameModel(ComboBoxModel):
    def _populate_items(self):
        ...
class VariabilityItem(omni.ui._ui.AbstractItem):
    def __init__(self, variability: pxr.Sdf.Variability, variability_str: str):
        ...
class VariabilityModel(ComboBoxModel):
    def _populate_items(self):
        ...
