from __future__ import annotations
from collections import OrderedDict
from omni.kit.property.usd.usd_property_widget import UsdPropertyUiEntry
__all__: list = list()
class Container:
    def __enter__(self):
        ...
    def __exit__(self, exc_type, exc_value, tb):
        ...
    def __init__(self, hide_if_true = None, show_if_true = None):
        ...
    def add_child(self, item):
        ...
    def get_collapsed(self):
        ...
    def get_name(self):
        ...
    def is_visible(self):
        ...
class CustomLayoutFrame(Container):
    def __init__(self, hide_extra = False):
        ...
    def _process_container(self, container, props_dict, customized_props, group_name):
        ...
    def apply(self, props):
        ...
class CustomLayoutGroup(Container):
    def __init__(self, container_name, collapsed = False, hide_if_true = None, show_if_true = None):
        ...
class CustomLayoutProperty:
    def __init__(self, prop_name, display_name = None, build_fn = None, hide_if_true = None, show_if_true = None):
        ...
    def get_build_fn(self):
        ...
    def get_display_name(self):
        ...
    def get_property_name(self):
        ...
    def is_visible(self):
        ...
stack: list = list()
