from __future__ import annotations
import carb as carb
from functools import partial
import math as math
import omni as omni
from omni.kit.property.physx.models import CustomMetadataObjectModel
from omni.kit.property.physx.models import TfTokenAttributeModelWMetadata
from omni.kit.property.physx.utils import Limits
from omni.kit.property.physx.utils import get_display_name
from omni.kit.property.usd.usd_attribute_model import GfQuatEulerAttributeModel
from omni.kit.property.usd.usd_attribute_model import TfTokenAttributeModel
from omni.kit.property.usd.usd_attribute_model import UsdAttributeModel
from omni.kit.property.usd.usd_property_widget_builder import UsdPropertiesWidgetBuilder
from omni.physx.bindings import _physx as pxb
from omni.physx.scripts.pythonUtils import ScopeGuard
from omni import physxcommands as commands
from omni import ui
from pxr import Sdf
from pxr import Vt
import typing
__all__ = ['AngleWidgetBuilder', 'BitfieldWidgetBuilder', 'CustomMetadataObjectModel', 'CustomTokenComboBuilder', 'GearingWidgetBuilder', 'GfQuatEulerAttributeModel', 'HORIZONTAL_SPACING', 'HideWidgetBuilder', 'Limits', 'LocalSpaceVelocitiesWidgetBuilder', 'ModelWithWidgetBuilder', 'PrettyPrintTokenComboBuilder', 'QuatEulerRotationBuilder', 'ReferenceFrameIsCenterOfMassWidgetBuilder', 'RelationshipWidgetBuilder', 'ScopeGuard', 'Sdf', 'TfTokenAttributeModel', 'TfTokenAttributeModelWMetadata', 'UsdAttributeModel', 'UsdPropertiesWidgetBuilder', 'Vt', 'carb', 'commands', 'get_display_name', 'math', 'omni', 'partial', 'pxb', 'ui']
class AngleWidgetBuilder(omni.kit.property.usd.usd_attribute_model.UsdAttributeModel):
    def __init__(self, stage, prop, prim_paths, label_kwargs, widget_kwargs):
        ...
class BitfieldWidgetBuilder(omni.kit.property.usd.usd_attribute_model.UsdAttributeModel):
    def __init__(self, stage, prop, prim_paths, label_kwargs, widget_kwargs, bits):
        ...
    def _gather_value(self):
        ...
    def _scatter_value(self):
        ...
class CustomTokenComboBuilder(PrettyPrintTokenComboBuilder):
    def __init__(self, stage, prop, prim_paths, label_kwargs, widget_kwargs, custom_names):
        ...
    def _get_allowed_tokens(self, _):
        ...
class GearingWidgetBuilder(omni.kit.property.usd.usd_attribute_model.UsdAttributeModel):
    def __init__(self, stage, prop, prim_paths, label_kwargs, widget_kwargs):
        ...
    def get_first_array_item_as_float(self) -> float:
        ...
class HideWidgetBuilder(omni.kit.property.usd.usd_attribute_model.UsdAttributeModel):
    def __init__(self, stage, prop, prim_paths, label_kwargs, widget_kwargs):
        ...
class LocalSpaceVelocitiesWidgetBuilder(omni.kit.property.physx.models.CustomMetadataObjectModel):
    def __init__(self, stage, prop, prim_paths, label_kwargs, widget_kwargs, name):
        ...
    def _cb_value_changed_fn(self, value):
        ...
    def _get_default_value(self):
        ...
    def _reflect_current_state_in_ui(self):
        ...
    def _reset_to_default(self):
        ...
    def _undo_redo_on_change(self, cmds):
        ...
    def _update_ui_state(self):
        ...
    def clean(self):
        ...
    def on_velocities_settings_changed(self, item, event_type):
        ...
class ModelWithWidgetBuilder(omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder):
    default_range_steps: typing.ClassVar[dict] = {}
    widget_builder_coverage_table: typing.ClassVar[dict]  # value = {Tf.Type.FindByName('pxr_half::half'): False, Tf.Type.FindByName('float'): False, Tf.Type.FindByName('double'): False, Tf.Type.FindByName('unsigned char'): False, Tf.Type.FindByName('unsigned int'): False, Tf.Type.FindByName('int'): False, Tf.Type.FindByName('long'): False, Tf.Type.FindByName('unsigned long'): False, Tf.Type.FindByName('bool'): False, Tf.Type.FindByName('VtArray<bool>'): False, Tf.Type.FindByName('string'): False, Tf.Type.FindByName('GfMatrix2d'): False, Tf.Type.FindByName('GfMatrix3d'): False, Tf.Type.FindByName('GfMatrix4d'): False, Tf.Type.FindByName('GfVec2i'): False, Tf.Type.FindByName('GfVec2h'): False, Tf.Type.FindByName('GfVec2f'): False, Tf.Type.FindByName('GfVec2d'): False, Tf.Type.FindByName('GfVec3i'): False, Tf.Type.FindByName('GfVec3h'): False, Tf.Type.FindByName('GfVec3f'): False, Tf.Type.FindByName('GfVec3d'): False, Tf.Type.FindByName('GfVec4i'): False, Tf.Type.FindByName('GfVec4h'): False, Tf.Type.FindByName('GfVec4f'): False, Tf.Type.FindByName('GfVec4d'): False, Tf.Type.FindByName('TfToken'): False, Tf.Type.FindByName('SdfAssetPath'): False, Tf.Type.FindByName('SdfTimeCode'): False, Tf.Type.FindByName('VtArray<SdfAssetPath>'): False}
    widget_builder_table: typing.ClassVar[dict]  # value = {Tf.Type.FindByName('pxr_half::half'): ModelWithWidgetBuilder.floating_point_builder, Tf.Type.FindByName('float'): ModelWithWidgetBuilder.floating_point_builder, Tf.Type.FindByName('double'): ModelWithWidgetBuilder.floating_point_builder, Tf.Type.FindByName('unsigned char'): ModelWithWidgetBuilder.integer_builder, Tf.Type.FindByName('unsigned int'): ModelWithWidgetBuilder.integer_builder, Tf.Type.FindByName('int'): ModelWithWidgetBuilder.integer_builder, Tf.Type.FindByName('long'): ModelWithWidgetBuilder.integer_builder, Tf.Type.FindByName('unsigned long'): ModelWithWidgetBuilder.integer_builder, Tf.Type.FindByName('bool'): ModelWithWidgetBuilder.bool_builder, Tf.Type.FindByName('VtArray<bool>'): omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder.bool_array_builder, Tf.Type.FindByName('string'): omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder.string_builder, Tf.Type.FindByName('GfMatrix2d'): omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder.gf_matrix_builder, Tf.Type.FindByName('GfMatrix3d'): omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder.gf_matrix_builder, Tf.Type.FindByName('GfMatrix4d'): omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder.gf_matrix_builder, Tf.Type.FindByName('GfVec2i'): omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder.vec2_per_channel_builder, Tf.Type.FindByName('GfVec2h'): omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder.vec2_per_channel_builder, Tf.Type.FindByName('GfVec2f'): omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder.vec2_per_channel_builder, Tf.Type.FindByName('GfVec2d'): omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder.vec2_per_channel_builder, Tf.Type.FindByName('GfVec3i'): omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder.vec3_per_channel_builder, Tf.Type.FindByName('GfVec3h'): omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder.vec3_per_channel_builder, Tf.Type.FindByName('GfVec3f'): omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder.vec3_per_channel_builder, Tf.Type.FindByName('GfVec3d'): omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder.vec3_per_channel_builder, Tf.Type.FindByName('GfVec4i'): omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder.vec4_per_channel_builder, Tf.Type.FindByName('GfVec4h'): omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder.vec4_per_channel_builder, Tf.Type.FindByName('GfVec4f'): omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder.vec4_per_channel_builder, Tf.Type.FindByName('GfVec4d'): omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder.vec4_per_channel_builder, Tf.Type.FindByName('TfToken'): ModelWithWidgetBuilder.tftoken_builder, Tf.Type.FindByName('SdfAssetPath'): omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder.sdf_asset_path_builder, Tf.Type.FindByName('SdfTimeCode'): omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder.time_code_builder, Tf.Type.FindByName('VtArray<SdfAssetPath>'): omni.kit.property.usd.usd_property_widget_builder.UsdPropertiesWidgetBuilder.sdf_asset_path_array_builder}
    @classmethod
    def __new__(cls, stage, prop, prim_paths, label_kwargs, widget_kwargs):
        ...
    @classmethod
    def bool_builder(cls, stage, attr_name, type_name, metadata, prim_paths, additional_label_kwargs = None, additional_widget_kwargs = None):
        ...
    @classmethod
    def floating_point_builder(cls, stage, attr_name, type_name, metadata, prim_paths, additional_label_kwargs = None, additional_widget_kwargs = None):
        ...
    @classmethod
    def integer_builder(cls, stage, attr_name, type_name, metadata, prim_paths, additional_label_kwargs = None, additional_widget_kwargs = None):
        ...
    @classmethod
    def tftoken_builder(cls, stage, attr_name, type_name, metadata, prim_paths, additional_label_kwargs = None, additional_widget_kwargs = None):
        ...
class PrettyPrintTokenComboBuilder(omni.kit.property.physx.models.TfTokenAttributeModelWMetadata):
    def __init__(self, stage, prop, prim_paths, label_kwargs, widget_kwargs, pretty_names, additions = list()):
        ...
    def _update_allowed_token(self):
        ...
class QuatEulerRotationBuilder(omni.kit.property.usd.usd_attribute_model.GfQuatEulerAttributeModel):
    def __init__(self, stage, prop, prim_paths, label_kwargs, widget_kwargs):
        ...
class ReferenceFrameIsCenterOfMassWidgetBuilder(omni.kit.property.physx.models.CustomMetadataObjectModel):
    def __init__(self, stage, prop, prim_paths, label_kwargs, widget_kwargs, name):
        ...
    def _cb_value_changed_fn(self, value):
        ...
    def _get_default_value(self):
        ...
    def _reflect_current_state_in_ui(self):
        ...
    def _reset_to_default(self):
        ...
    def _undo_redo_on_change(self, cmds):
        ...
    def _update_ui_state(self):
        ...
    def clean(self):
        ...
def RelationshipWidgetBuilder(stage, prop, prim_paths, label_kwargs, widget_kwargs, filter_types = list(), targets_limit = 0, filter_fn = None, target_name = None):
    ...
HORIZONTAL_SPACING: int = 4
