"""

this file is full of prototypes/modification of external classes that would be impossible to
readably modify with inheritance, all of this would eventually be re/moved and replaced by
proper external depedency
"""
from __future__ import annotations
import omni as omni
__all__ = ['Prompt', 'omni']
class Prompt:
    def __del__(self):
        ...
    def __enter__(self):
        ...
    def __exit__(self, type, value, trace):
        ...
    def __init__(self, title, text, ok_button_text = 'OK', cancel_button_text = None, middle_button_text = None, ok_button_fn = None, cancel_button_fn = None, middle_button_fn = None, modal = False):
        ...
    def _build_ui(self):
        ...
    def _on_cancel_button_fn(self):
        ...
    def _on_middle_button_fn(self):
        ...
    def _on_ok_button_fn(self):
        ...
    def hide(self):
        ...
    def is_visible(self):
        ...
    def set_cancel_fn(self, on_cancel_button_clicked):
        ...
    def set_confirm_fn(self, on_ok_button_clicked):
        ...
    def set_middle_button_fn(self, on_middle_button_clicked):
        ...
    def set_text(self, text):
        ...
    def show(self):
        ...
