from __future__ import annotations
import omni.kit.property.usd.usd_attribute_model
from omni.kit.property.usd.usd_attribute_model import TfTokenAttributeModel
from omni.physx.scripts import utils
from omni import physxcommands as commands
__all__ = ['CustomMetadataObjectModel', 'TfTokenAttributeModel', 'TfTokenAttributeModelWMetadata', 'commands', 'utils']
class CustomMetadataObjectModel:
    def __init__(self, stage, prop, prim_paths, metadata_name):
        ...
    def _clear_metadata(self, object):
        ...
    def _determine_value(self):
        ...
    def _get_default_value(self):
        ...
    def _get_metadata_or_default(self, object):
        ...
    def _get_objects(self):
        ...
    def _set_metadata(self, object, value):
        ...
    def clean(self):
        ...
    def get_info_str(self):
        ...
    def get_value(self):
        ...
    def is_ambiguous(self):
        ...
    def set_value(self, value, clear_metadata_when_possible = False):
        ...
class TfTokenAttributeModelWMetadata(omni.kit.property.usd.usd_attribute_model.TfTokenAttributeModel):
    def _get_allowed_tokens(self, attr):
        ...
