from __future__ import annotations
from omni.kit.async_engine.async_engine import run_coroutine
from pxr import Sdf
from pxr import Usd
import re as re
__all__: list = ['aio_open_layer', 'aio_re_find_all', 'aio_replace_all', 'aio_save_layer', 'aio_re_sub_all']
def _run_asyncio(sync_fn, *args, **kwargs):
    ...
def _run_replacement(s, old_text, new_text, exact_match = False):
    ...
def aio_open_layer(path):
    ...
def aio_re_find_all(regex, content):
    ...
def aio_re_sub_all(s, pattern, replace):
    ...
def aio_replace_all(s, old_text, new_text, exact_match = False):
    ...
def aio_save_layer(layer):
    ...
