from __future__ import annotations
import omni.kit.tool.asset_importer.importers_manager
from omni.kit.tool.asset_importer.importers_manager import ImportersManager
from omni.kit.window import content_browser as content
from omni import ui
import os as os
from pathlib import Path
__all__ = ['ENABLE_FARM_SUBMISSION', 'ImportersManager', 'OptionsWindow', 'Path', 'content', 'os', 'ui']
class OptionsWindow:
    def __init__(self, usd_context, importers_manager: omni.kit.tool.asset_importer.importers_manager.ImportersManager, modal = False):
        ...
    def _build_window(self):
        ...
    def _collect_tasks(self) -> typing.List[ForwardRef('TaskDefinition')]:
        ...
    def _get_current_dir_in_content_window(self):
        ...
    def _get_export_folder(self):
        ...
    def _on_cancel_fn(self):
        ...
    def _on_import_fn(self):
        ...
    def destroy(self):
        ...
    def hide(self):
        ...
    def set_import_fn(self, import_fn):
        ...
    def show(self, asset_paths, export_to_current_folder = True):
        ...
    @property
    def visible(self):
        ...
ENABLE_FARM_SUBMISSION: bool = False
