from __future__ import annotations
from omni import ui
import omni.ui._ui
__all__ = ['CustomProgressModel', 'ProgressPopup', 'ui']
class CustomProgressModel(omni.ui._ui.AbstractValueModel):
    def __init__(self):
        ...
    def get_value_as_float(self):
        ...
    def get_value_as_string(self):
        ...
    def set_value(self, value):
        """
        Reimplemented set
        """
class ProgressPopup:
    """
    Creates a modal window with a status label and a progress bar inside.
    
        Args:
            title (str): Title of this window.
            cancel_button_text (str): It will have a cancel button by default. This is the title of it.
            cancel_button_fn (function): The callback after cancel button is clicked.
            status_text (str): The status text.
            min_value: The min value of the progress bar. It's 0 by default.
            max_value: The max value of the progress bar. It's 100 by default.
            dark_style: If it's to use dark style or light style. It's dark stye by default.
        
    """
    progress = ...
    status_text = ...
    def __enter__(self):
        ...
    def __exit__(self, type, value, trace):
        ...
    def __init__(self, title, cancel_button_text = 'CANCEL', cancel_button_fn = None, status_text = '', modal = True):
        ...
    def _build_ui(self):
        ...
    def _on_cancel_button_fn(self):
        ...
    def destroy(self):
        ...
    def get_progress(self):
        ...
    def get_status_text(self):
        ...
    def hide(self):
        ...
    def is_visible(self):
        ...
    def set_cancel_fn(self, on_cancel_button_clicked):
        ...
    def set_progress(self, progress):
        ...
    def set_status_text(self, status_text):
        ...
    def show(self):
        ...
