from __future__ import annotations
import omni as omni
from omni.kit.manipulator.selection.manipulator import SelectionManipulator
from omni.kit.manipulator.selection.manipulator import SelectionMode
__all__: list = ['SelectionManipulatorItem']
class SelectionManipulatorItem:
    visible: bool
    def _SelectionManipulatorItem__handle_selection(self, model, ndc_rect, mode, viewport_api):
        ...
    def _SelectionManipulatorItem__model_changed(self, model, item) -> None:
        ...
    def _SelectionManipulatorItem__request_pick(self) -> None:
        ...
    def _SelectionManipulatorItem__reset_state(self) -> None:
        ...
    def __init__(self, desc: dict, *args, **kwargs):
        ...
    def destroy(self):
        ...
    @property
    def categories(self) -> typing.Sequence:
        ...
    @property
    def name(self) -> str:
        ...
