from __future__ import annotations
import typing
import usdrt.Gf._Gf
import usdrt.Sdf._Sdf
import usdrt.Usd._Usd
__all__ = ['Boundable', 'ChangeTracker', 'RtPrimSelection', 'Tokens', 'Xformable']
class Boundable(Xformable):
    def ClearWorldExtent(self) -> bool:
        ...
    def CreateWorldExtentAttr(self, defaultValue: usdrt.Gf._Gf.Range3d = ...) -> usdrt.Usd._Usd.Attribute:
        ...
    def GetWorldExtentAttr(self) -> usdrt.Usd._Usd.Attribute:
        ...
    def HasWorldExtent(self) -> bool:
        ...
    def SetWorldExtentFromUsd(self) -> bool:
        ...
    def __init__(self, prim: usdrt.Usd._Usd.Prim = ...) -> None:
        ...
    def __repr__(self: Xformable) -> str:
        ...
class ChangeTracker:
    @typing.overload
    def AttributeChanged(self, attr: usdrt.Usd._Usd.Attribute) -> bool:
        ...
    @typing.overload
    def AttributeChanged(self, attrPath: usdrt.Sdf._Sdf.Path) -> bool:
        ...
    def ClearChanges(self) -> None:
        ...
    def EnablePrimCreateTracking(self) -> None:
        ...
    def GetAddedPrims(self) -> list[usdrt.Sdf._Sdf.Path]:
        ...
    def GetAllChangedAttributes(self) -> list[usdrt.Sdf._Sdf.Path]:
        ...
    def GetAllChangedPrims(self) -> list[usdrt.Sdf._Sdf.Path]:
        ...
    @typing.overload
    def GetChangedAttributes(self, prim: usdrt.Usd._Usd.Prim) -> list[TfToken]:
        ...
    @typing.overload
    def GetChangedAttributes(self, primPath: usdrt.Sdf._Sdf.Path) -> list[TfToken]:
        ...
    def GetTrackedAttributes(self) -> list[TfToken]:
        ...
    def HasChanges(self) -> bool:
        ...
    def IsChangeTrackingPaused(self) -> bool:
        ...
    def IsTrackingAttribute(self, attrName: TfToken) -> bool:
        ...
    def PauseTracking(self) -> None:
        ...
    @typing.overload
    def PrimChanged(self, prim: usdrt.Usd._Usd.Prim) -> bool:
        ...
    @typing.overload
    def PrimChanged(self, primPath: usdrt.Sdf._Sdf.Path) -> bool:
        ...
    def ResumeTracking(self) -> None:
        ...
    def StopTrackingAttribute(self, attrName: TfToken) -> None:
        ...
    def TrackAttribute(self, attrName: TfToken) -> None:
        ...
    def __init__(self, arg0: usdrt.Usd._Usd.Stage) -> None:
        ...
class RtPrimSelection:
    def GetCount(self) -> int:
        ...
    def GetPaths(self) -> list[usdrt.Sdf._Sdf.Path]:
        ...
    def PrepareForReuse(self) -> bool:
        ...
    @property
    def __fabric_arrays_interface__(self) -> dict:
        ...
class Tokens:
    fabricHierarchyLocalMatrix: typing.ClassVar[str] = 'omni:fabric:localMatrix'
    fabricHierarchyWorldMatrix: typing.ClassVar[str] = 'omni:fabric:worldMatrix'
    localMatrix: typing.ClassVar[str] = '_localMatrix'
    worldExtent: typing.ClassVar[str] = '_worldExtent'
    worldOrientation: typing.ClassVar[str] = '_worldOrientation'
    worldPosition: typing.ClassVar[str] = '_worldPosition'
    worldScale: typing.ClassVar[str] = '_worldScale'
class Xformable:
    def ClearLocalXform(self) -> bool:
        ...
    def ClearWorldXform(self) -> bool:
        ...
    def CreateFabricHierarchyLocalMatrixAttr(self, defaultValue: usdrt.Gf._Gf.Matrix4d = ...) -> usdrt.Usd._Usd.Attribute:
        ...
    def CreateFabricHierarchyWorldMatrixAttr(self, defaultValue: usdrt.Gf._Gf.Matrix4d = ...) -> usdrt.Usd._Usd.Attribute:
        ...
    def CreateLocalMatrixAttr(self, defaultValue: usdrt.Gf._Gf.Matrix4d = ...) -> usdrt.Usd._Usd.Attribute:
        ...
    def CreateWorldOrientationAttr(self, defaultValue: usdrt.Gf._Gf.Quatf = ...) -> usdrt.Usd._Usd.Attribute:
        ...
    def CreateWorldPositionAttr(self, defaultValue: usdrt.Gf._Gf.Vec3d = ...) -> usdrt.Usd._Usd.Attribute:
        ...
    def CreateWorldScaleAttr(self, defaultValue: usdrt.Gf._Gf.Vec3f = ...) -> usdrt.Usd._Usd.Attribute:
        ...
    def GetFabricHierarchyLocalMatrixAttr(self) -> usdrt.Usd._Usd.Attribute:
        ...
    def GetFabricHierarchyWorldMatrixAttr(self) -> usdrt.Usd._Usd.Attribute:
        ...
    def GetLocalMatrixAttr(self) -> usdrt.Usd._Usd.Attribute:
        ...
    def GetPath(self) -> usdrt.Sdf._Sdf.Path:
        ...
    def GetPrim(self) -> usdrt.Usd._Usd.Prim:
        ...
    def GetWorldOrientationAttr(self) -> usdrt.Usd._Usd.Attribute:
        ...
    def GetWorldPositionAttr(self) -> usdrt.Usd._Usd.Attribute:
        ...
    def GetWorldScaleAttr(self) -> usdrt.Usd._Usd.Attribute:
        ...
    def HasLocalXform(self) -> bool:
        ...
    def HasWorldXform(self) -> bool:
        ...
    def SetLocalXformFromUsd(self) -> bool:
        ...
    def SetWorldXformFromUsd(self) -> bool:
        ...
    def __bool__(self) -> bool:
        ...
    def __init__(self, prim: usdrt.Usd._Usd.Prim = ...) -> None:
        ...
    def __repr__(self) -> str:
        ...
