from __future__ import annotations
from omni import ui
import omni.ui._ui
__all__ = ['LayerLiveUpdateModel', 'ui']
class LayerLiveUpdateModel(omni.ui._ui.AbstractValueModel):
    def __init__(self, usd_context, layer_item):
        ...
    def destroy(self):
        ...
    def get_value_as_bool(self):
        ...
    def set_value(self, value):
        ...
