from __future__ import annotations
from omni import ui
import omni.ui._ui
__all__ = ['LayerNameModel', 'ui']
class LayerNameModel(omni.ui._ui.AbstractValueModel):
    def __init__(self, layer_item):
        ...
    def destroy(self):
        ...
    def get_value_as_string(self):
        ...
    def set_value(self, value):
        ...
