from __future__ import annotations
from omni.kit.usd import layers
import omni.kit.usd.layers._impl.live_session_channel_manager
from omni import ui
import omni.ui._ui
__all__ = ['LiveSessionUserModel', 'layers', 'ui']
class LiveSessionUserModel(omni.ui._ui.AbstractValueModel):
    peer_user = ...
    def __init__(self, peer_user: omni.kit.usd.layers._impl.live_session_channel_manager.LiveSessionUser):
        ...
    def destroy(self):
        ...
    def get_value_as_string(self):
        ...
    def set_value(self, value):
        ...
