from __future__ import annotations
import asyncio as asyncio
import carb as carb
import omni as omni
from omni.kit.widget.stage.export_utils import ExportPrimUSD
__all__: list = ['ActionManager']
class Action:
    def __init__(self, extension_name: str, action_name: str, action_display_name: str, action_description: str, on_action_fn: typing.Callable[[], NoneType], hotkey: carb.input.KeyboardInput = None, modifiers: int = 0):
        ...
    def _register(self):
        ...
    def _register_hotkey(self):
        ...
    def _unregister_hotkey(self):
        ...
    def destroy(self):
        ...
class ActionManager:
    def _ActionManager__register_hotkeys(self):
        ...
    def _ActionManager__unregister_hotkeys(self):
        ...
    def __init__(self):
        ...
    def on_shutdown(self):
        ...
    def on_startup(self):
        ...
def post_notification(message: str, info: bool = False, duration: int = 3):
    ...
def save_prim(objects = None):
    ...
def toggle_prims_active_state(prim_list = None, stage_model = None):
    ...
ACTIONS_TAG: str = 'Stage Actions'
ACTION_SAVE_PRIM: str = 'save_prim'
ACTION_TOGGLE_PRIMS_ACTIVE_STATE: str = 'toggle_prims_active_state'
